repository_type: pipeline

nf_core_version: 3.1.1

lint: {}

template:
  org: nf-core
  name: test
  description: Example of an issue
  author: tester
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
